### ISSUE TITLE
Enable creation of financial accounts

### ISSUE THREAD

**Issue by Merlin-55** [Stiehl-seine-Perlen/Benevolo#10]
>I as club manager want to create financial accounts to be able to link them to my clubs financial transactions.

### Acceptance criteria
- name of financial account is persisted
- financial account has a short reference
- club manager can reference/use account for booking transactions

### Hints
- collect required data according to our data scheme

**Comment by Ph1L42** [comment]
Folge Ticket für Anbindung mit Association
