### ISSUE TITLE
SetUp and DevOps

### ISSUE THREAD

**Issue by Ph1L42** [Stiehl-seine-Perlen/Benevolo#25]
>I as developer Daniela want to have an overview over our tech stack to be able to present it to our team when a DevOps topic comes up.

### Acceptance criteria
- at least 2 people are involved in the DevOps topic
- tech stack is persisted in our doc in presentable form (list or graph or smth else)

### Subtasks
- [ ] investigate
- [ ] fix
- [ ] present findings to team

**Comment by janvorhoff** [comment]
Unter https://github.com/Stiehl-seine-Perlen/infrastructure/blob/main/README.md ist nun eine kleine documentation über den ablauf der pipeline als auch die architektur zu finden.
