### ISSUE TITLE
IO service for minIO

### ISSUE THREAD

**Issue by Ph1L42** [Stiehl-seine-Perlen/Benevolo#34]
>I as dev David want to be able to call a service to which I can upload files to have them stored for later processing.

### acceptance criteria
- api we can send files to
- files are stored in our minIO
- implementation in entities repo
- reusable for everyone

### subtasks

**Comment by janvorhoff** [comment]
Upload ist schon möglich. 
Wir wollen uns am Dienstag aber noch einmal über die Implementierungsdetails mit Markus unterhalten.
