### ISSUE TITLE
Create registration for associations

### ISSUE THREAD

**Issue by Merlin-55** [Stiehl-seine-Perlen/Benevolo#4]
>I as business client want to be able to register my association for the application services to be able to reach potential members.

### Acceptance criteria
- Name
- Register number (Amtsgericht)
- Address
- Contact mail
- About text
- tags

### Hints
- Daniels design
- tags can be understood like hashtags. Topics that are supposed to make it easier for potential members to browse through the assocs.

### Subtasks
- [ ] develop
- [ ] test
- [ ] deploy

**Comment by MatthiasRaimann** [comment]
Warum sind hier 3 Leute assigned?

**Comment by MaximilianRu** [comment]
Übersicht der zu befüllenden Felder für eine Vereinsgründung: 

- [x] Vereinsname
- [x] Registernummer
- [x] Email
- [ ] Über
- [ ] Logo (Bilddatei)
- [ ] Adresse
- [ ] - Straße / Hausnummer
- [ ] - Plz / Stadt
- [ ] - Land
