### ISSUE TITLE
Create landing page

### ISSUE THREAD

**Issue by Merlin-55** [Stiehl-seine-Perlen/Benevolo#8]
>I as customer Carl want to be able to look at a landing page that lists the applications services to have en entry point to the app. 

### Acceptance criteria
- [x] Landing page lists services
- [x] Landing page leads to registration
- [x] Landing page leads to sign in

**Comment by Ph1L42** [comment]
Karussel

**Comment by MatthiasRaimann** [comment]
Welche Features soll ich denn angeben? @Merlin-55

**Comment by ghost** [comment]
#### User
-  Vereine finden
- updates erhalten
- Anmeldung bei Veranstaltungen

#### Assoc/Assoc Managment
- Promote your Assoc on your own page
- manage your events
- manage your financial accounts

**Comment by ghost** [comment]
Looks fine to me 👍 

I'll add content at a later point in time but this would be a small & lean business story.

Good work!
